### ISSUE TITLE
Getting 429 all the time

### ISSUE THREAD

**Issue by yagizcamo93** [alfonsrv/impf-botpy#67]
Hi, 
first of all thanks for the program.
I completed the setup and then ran the program and it's running for a while now. I realised that I'm getting 429- shadow bans all the time. Is there anything that I can do?
Don't know if it's the right log file but here it is:
[bot.log](https://github.com/alfonsrv/impf-botpy/files/6650166/bot.log)

**Comment by alfonsrv** [comment]
You running in Docker?

**Comment by yagizcamo93** [comment]
No, I don't use any optional feature

**Comment by pttrck68** [comment]
Hi, first of all: I managed to get some appointments for family & friends with the program over the last week- thank you so much for this! 

However, since the last weekend, I'm running in the same issue though. Immediately getting 429 after starting. No matter from which device or network I run it. Any advice?

**Comment by javiser** [comment]
I have a similar experience to report. Last week I got some appointments but since yesterday I get a lot of 429 errors, so far no luck at all with the appointments. However, I don't get always the errors, just very often, and it appears that some locations are more prone to show the error than others. I use concurrent windows, in case this is important to mention.

**Comment by alfonsrv** [comment]
I've got 3 appointments today; so the searching process is not impacted. I was also able to generate multiple Vermittlungscodes during the day using the latest version.  

Since those are the only two processes that matter, I don't see an issue here tbh.  

Generally, the more people are requesting the website and using the bot, the more likely you are to get `429` (duh). 
You could test if the bot is at fault by trying via a regular browser. But as mentioned above the main parts of the process are definitely not impacted.
